# name = input("enter your full name")
phone_no = (input("enter the phone number:"))
# result = len(name)  ##(give the length include spaces too)
result = phone_no.find(" ")  ##(give the first occurence of value)
# result = name.rfind("o") ##(give the last  occurence of value)
# result= name.capitalize()  ##(it capitalize only first letter)
# result = name.upper() ##(capitalize all the characters)
# result = name.lower() ##(small all the characters)
# result = name.isdigit() ##(if contains only digits then true else false)
# result = name.isalpha()   ##(if contains only alphabet and no space then true else false)
# result = phone_no.count("~") ##(count the particular given element)
# result = phone_no.replace("~"," ")
print(result) 